version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  apt_packages:
    - python3-newt

python:
  install:
    - method: setuptools
      path: .
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
